Add pick function
js-tasks-ru/js-20200928_bbbom pull request #2
Opened 2020-10-03 14:38 UTC by azozulya

Add pick function

2020-10-03 14:47 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-10-03 18:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-04 15:15 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  if (Object.keys(obj).length === 0 || keys.length === 0) return {};
эта проверка лишняя, если мы будем выполнять метод `forEach` на пустом массиве, то  переданный колбек не отработает ни разу

2020-10-04 15:16 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const newObj = [];
нельзя называть переменную `newObj` и присваивать в нее массив. Получается что название не совпадает с тем что находится внутри переменной

2020-10-04 15:17 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  return newObj.length > 0 ? Object.fromEntries(newObj) : {};
почему бы не избавиться от `Object.fromEntries`?
Подумайте ведь мы сразу можем объявить пустой объект и складывать в него нужные значения, зачем нам дополнительно делать преобразования объекта к массиву и назад?

2020-10-04 15:18 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).forEach( ([key, val]) => {
замечания аналогичны решению `pick`

2020-10-04 15:18 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-04 18:27 UTC, azozulya commented on 02-javascript-data-types/2-pick/index.js
> +  if (Object.keys(obj).length === 0 || keys.length === 0) return {};
Убрала

2020-10-04 18:27 UTC, azozulya commented on 02-javascript-data-types/2-pick/index.js
> +  const newObj = [];
Поправила

2020-10-04 18:28 UTC, azozulya commented on 02-javascript-data-types/2-pick/index.js
> +  return newObj.length > 0 ? Object.fromEntries(newObj) : {};
Действительно, согласна) Не знаю почему так сделала

2020-10-04 18:29 UTC, azozulya commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).forEach( ([key, val]) => {
Поправила

2020-10-04 18:29 UTC, azozulya commented
Добавила правки!

2020-10-05 08:29 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return a new sorted array
- should return sorted by "asc" array of strings
- should return sorted by "desc" array of strings in "en" locale
- should correctly sort language-specific characters in "ru" locale
- should correctly sort strings started from uppercase
- should correctly sort strings for mixed "en" and "ru" locales
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

2020-10-05 12:14 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return sorted by "desc" array of strings in "en" locale
+ should correctly sort language-specific characters in "ru" locale
+ should correctly sort strings started from uppercase
+ should correctly sort strings for mixed "en" and "ru" locales
- should return a new sorted array
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

2020-10-05 13:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-06 14:03 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return b.localeCompare(a, 'ru', {caseFirst: 'upper'});
Пожалуйста добавьте `en` локаль для сортировки:
```
localeCompare(a, ['ru', 'en'] {caseFirst: 'upper'});
```

2020-10-06 14:04 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return a.localeCompare(b, 'ru', {caseFirst: 'upper'});
строка 12 дублирует строку 14 за исключением порядка `a` и `b` при вызове `localCompare`.
Попробуйте избавиться от дубликатов кода.

2020-10-06 14:06 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  const keys = [...fields];
это лишняя операция. `fields` в данном случае это итерируемая структура, которую можно обойти с помощью `for...of` цикла

2020-10-06 14:06 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  const keys = [...fields];
аналогичный комментарий в `pick`

2020-10-06 14:06 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-10-06 19:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 06:48 UTC, azozulya commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return b.localeCompare(a, 'ru', {caseFirst: 'upper'});
Добавила

2020-10-07 06:48 UTC, azozulya commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return a.localeCompare(b, 'ru', {caseFirst: 'upper'});
Поправила

2020-10-07 06:49 UTC, azozulya commented on 02-javascript-data-types/2-pick/index.js
> +  const keys = [...fields];
поправила

2020-10-07 06:49 UTC, azozulya commented on 02-javascript-data-types/3-omit/index.js
> +  const keys = [...fields];
Fix

2020-10-07 12:19 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 12:32 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 12:42 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 15:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-07 18:36 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return [...new Set(arr)];
good 👍

2020-10-07 18:37 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +// console.log(trimSymbols('xxx', 2)); // 'xx' - удалили один символ
не оставляйте закомментированный код в PR - это плохая практика

2020-10-07 18:38 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +// console.log(trimSymbols('xxx', 2)); // 'xx' - удалили один символ
код должен говорить сам за себя, и комментарии допустимы только в очень редких случаях.
Что касается отладочных вызовов типа `console.log` их в PR точно не должно быть

2020-10-07 18:38 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
>  export function trimSymbols(string, size) {
решение принимается, но обратите внимание на разбор данной задачи на занятии

2020-10-07 18:38 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +  if(!obj) return;
good 👍

2020-10-07 18:38 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const fields = path.split('.');
было бы неплохо вынести `path.split('.')` в родительскую функцию, иначе данная операция будет выполняться каждый раз при вызове геттера, хотя данное значение требуется рассчитать только один раз при создании геттера

2020-10-07 18:39 UTC, dosandk requested changes
все решениея кроме createGetter принимаются, посмотрите коммент

2020-10-08 06:12 UTC, azozulya commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    const fields = path.split('.');
Поправила

2020-10-08 06:13 UTC, azozulya commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +// console.log(trimSymbols('xxx', 2)); // 'xx' - удалили один символ
Поняла, удалила комментарии

2020-10-08 06:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-10-09 20:02 UTC, dosandk approved these changes
good 👍

2020-10-09 20:03 UTC, merged